### ISSUE TITLE
Email not sending

### ISSUE THREAD

**Issue by andyg2** [vteams/open-source-billing#45]
Despite the message:  `Invoice sent successfully.`, no negotiation with the mail server takes place.
My mail server only accepts connections over SSL 

```
  smtp_setting:
     address: 'domain.com'
     port: 587
     authentication: :plain,
     enable_starttls_auto: true,
     user_name: 'me@domain.com',
     password: '123456789'
```

I have also tried adding but it makes no difference:

```
     ssl: true
     authentication: :login,
```

In fact no matter what settings I use, the system always reports the invoice was sent but it isn't.

How can I debug this or at least see a transaction log?

**Comment by Suneel-NXVT** [comment]
Kindly pull the latest code. Basically syntax error in smtp_setting in previous release. You can update the config.yml with latest config.yml.copy  or replace smtp_setting code with below code:

```
smtp_setting:
     address: 'smtp.gmail.com'
     port: 587
     authentication: :plain
     enable_starttls_auto: true
     user_name: 'YOUR_EMAIL_HERE'
     password: 'YOUR_PASSWORD_HERE'
```
